//go:build go1.22

// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apigen

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Facility defines model for Facility.
type Facility struct {
	Id       openapi_types.UUID `json:"id"`
	Name     string             `json:"name"`
	Timezone string             `json:"timezone"`
}

// FarmState defines model for FarmState.
type FarmState struct {
	Alerts               []map[string]interface{} `json:"alerts"`
	AutomationRules      []map[string]interface{} `json:"automation_rules"`
	ChannelBindings      []map[string]interface{} `json:"channel_bindings"`
	Channels             []map[string]interface{} `json:"channels"`
	Commands             []map[string]interface{} `json:"commands"`
	Crops                []map[string]interface{} `json:"crops"`
	Devices              []map[string]interface{} `json:"devices"`
	EventQuantities      []map[string]interface{} `json:"event_quantities"`
	Events               []map[string]interface{} `json:"events"`
	Facilities           []Facility               `json:"facilities"`
	GrowCycles           []map[string]interface{} `json:"grow_cycles"`
	Harvests             []map[string]interface{} `json:"harvests"`
	InventoryAdjustments []map[string]interface{} `json:"inventory_adjustments"`
	InventoryItems       []map[string]interface{} `json:"inventory_items"`
	Measurements         []map[string]interface{} `json:"measurements"`
	Observations         []map[string]interface{} `json:"observations"`
	PlantPositions       []map[string]interface{} `json:"plant_positions"`
	RecipeStages         []map[string]interface{} `json:"recipe_stages"`
	RecipeVersions       []map[string]interface{} `json:"recipe_versions"`
	Recipes              []map[string]interface{} `json:"recipes"`
	Reservoirs           []map[string]interface{} `json:"reservoirs"`
	SceneLayouts         []map[string]interface{} `json:"scene_layouts"`
	Setpoints            []map[string]interface{} `json:"setpoints"`
	Varieties            []map[string]interface{} `json:"varieties"`
	Zones                []map[string]interface{} `json:"zones"`
}

// Health defines model for Health.
type Health struct {
	Checks *map[string]string `json:"checks,omitempty"`
	Status string             `json:"status"`
}

// Problem defines model for Problem.
type Problem struct {
	Code          string  `json:"code"`
	CorrelationId *string `json:"correlationId,omitempty"`
	Detail        string  `json:"detail"`
	Instance      *string `json:"instance,omitempty"`
	Status        int     `json:"status"`
	Title         string  `json:"title"`
	Type          string  `json:"type"`
}

// CreateCommandJSONBody defines parameters for CreateCommand.
type CreateCommandJSONBody struct {
	ExpiresAt       *time.Time                  `json:"expiresAt,omitempty"`
	Reason          string                      `json:"reason"`
	TargetChannelId openapi_types.UUID          `json:"targetChannelId"`
	Value           CreateCommandJSONBody_Value `json:"value"`
}

// CreateCommandParams defines parameters for CreateCommand.
type CreateCommandParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// CreateCommandJSONBodyValue0 defines parameters for CreateCommand.
type CreateCommandJSONBodyValue0 = float32

// CreateCommandJSONBodyValue1 defines parameters for CreateCommand.
type CreateCommandJSONBodyValue1 = bool

// CreateCommandJSONBody_Value defines parameters for CreateCommand.
type CreateCommandJSONBody_Value struct {
	union json.RawMessage
}

// ReplaceFarmStateParams defines parameters for ReplaceFarmState.
type ReplaceFarmStateParams struct {
	IfMatch *string `json:"If-Match,omitempty"`
}

// CreateCommandJSONRequestBody defines body for CreateCommand for application/json ContentType.
type CreateCommandJSONRequestBody CreateCommandJSONBody

// ReplaceFarmStateJSONRequestBody defines body for ReplaceFarmState for application/json ContentType.
type ReplaceFarmStateJSONRequestBody = FarmState

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List alerts
	// (GET /api/v1/alerts)
	ListAlerts(w http.ResponseWriter, r *http.Request)
	// List logical channels
	// (GET /api/v1/channels)
	ListChannels(w http.ResponseWriter, r *http.Request)
	// List commands
	// (GET /api/v1/commands)
	ListCommands(w http.ResponseWriter, r *http.Request)
	// Request a validated device command
	// (POST /api/v1/commands)
	CreateCommand(w http.ResponseWriter, r *http.Request, params CreateCommandParams)
	// List devices
	// (GET /api/v1/devices)
	ListDevices(w http.ResponseWriter, r *http.Request)
	// List farm events
	// (GET /api/v1/events)
	ListEvents(w http.ResponseWriter, r *http.Request)
	// List facilities
	// (GET /api/v1/facilities)
	ListFacilities(w http.ResponseWriter, r *http.Request)
	// List grow cycles
	// (GET /api/v1/grow-cycles)
	ListGrowCycles(w http.ResponseWriter, r *http.Request)
	// List measurements
	// (GET /api/v1/measurements)
	ListMeasurements(w http.ResponseWriter, r *http.Request)
	// Read the operational overview
	// (GET /api/v1/overview)
	GetOverview(w http.ResponseWriter, r *http.Request)
	// List reservoirs
	// (GET /api/v1/reservoirs)
	ListReservoirs(w http.ResponseWriter, r *http.Request)
	// Read the complete farm state
	// (GET /api/v1/state)
	GetFarmState(w http.ResponseWriter, r *http.Request)
	// Replace the complete farm state
	// (PUT /api/v1/state)
	ReplaceFarmState(w http.ResponseWriter, r *http.Request, params ReplaceFarmStateParams)
	// List zones
	// (GET /api/v1/zones)
	ListZones(w http.ResponseWriter, r *http.Request)
	// Check process liveness
	// (GET /health/live)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// Check dependency readiness
	// (GET /health/ready)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAlerts operation middleware
func (siw *ServerInterfaceWrapper) ListAlerts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAlerts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChannels operation middleware
func (siw *ServerInterfaceWrapper) ListChannels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCommands operation middleware
func (siw *ServerInterfaceWrapper) ListCommands(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCommands(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCommand operation middleware
func (siw *ServerInterfaceWrapper) CreateCommand(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateCommandParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCommand(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDevices operation middleware
func (siw *ServerInterfaceWrapper) ListDevices(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFacilities operation middleware
func (siw *ServerInterfaceWrapper) ListFacilities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFacilities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGrowCycles operation middleware
func (siw *ServerInterfaceWrapper) ListGrowCycles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGrowCycles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMeasurements operation middleware
func (siw *ServerInterfaceWrapper) ListMeasurements(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMeasurements(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOverview operation middleware
func (siw *ServerInterfaceWrapper) GetOverview(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOverview(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListReservoirs operation middleware
func (siw *ServerInterfaceWrapper) ListReservoirs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListReservoirs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFarmState operation middleware
func (siw *ServerInterfaceWrapper) GetFarmState(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFarmState(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceFarmState operation middleware
func (siw *ServerInterfaceWrapper) ReplaceFarmState(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ReplaceFarmStateParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceFarmState(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListZones operation middleware
func (siw *ServerInterfaceWrapper) ListZones(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListZones(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/alerts", wrapper.ListAlerts)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/channels", wrapper.ListChannels)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/commands", wrapper.ListCommands)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/commands", wrapper.CreateCommand)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/devices", wrapper.ListDevices)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/events", wrapper.ListEvents)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/facilities", wrapper.ListFacilities)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/grow-cycles", wrapper.ListGrowCycles)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/measurements", wrapper.ListMeasurements)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/overview", wrapper.GetOverview)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/reservoirs", wrapper.ListReservoirs)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/state", wrapper.GetFarmState)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/state", wrapper.ReplaceFarmState)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/zones", wrapper.ListZones)
	m.HandleFunc("GET "+options.BaseURL+"/health/live", wrapper.GetLiveness)
	m.HandleFunc("GET "+options.BaseURL+"/health/ready", wrapper.GetReadiness)

	return m
}
